events {}

http {
  resolver 127.0.0.11 ipv6=off valid=30s;

  server {
    listen 80;
    server_name _;

    set $interface_service http://interface:7789;
    set $api_service http://api:7777;
    set $auth_service http://auth:19000;

    client_max_body_size 60m;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = /_auth/admin {
      internal;
      proxy_pass $auth_service/users/verify-admin;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Original-URI $request_uri;
    }

    location /api/ {
      proxy_pass $api_service;
    }

    location /api-docs/ {
      proxy_pass $api_service;
    }

    location = /api-docs {
      proxy_pass $api_service;
    }

    location /auth/ {
      rewrite ^/auth/(.*)$ /$1 break;
      proxy_pass $auth_service;
    }

    location /auth-docs/ {
      proxy_pass $auth_service;
    }

    location /media/ {
      proxy_pass $api_service;
    }

    location /download/ {
      proxy_pass $api_service;
    }

    location /admin {
      auth_request /_auth/admin;
      error_page 401 = @login_redirect;
      error_page 403 = @login_redirect;
      proxy_pass $interface_service;
    }

    location @login_redirect {
      return 302 $scheme://$http_host/users/login?redirect=$uri;
    }

    location / {
      proxy_pass $interface_service;
    }
  }
}
